%%<br>
Web scraping from Wikipedia

In [1]:
wiki_url = 'https://en.wikipedia.org/wiki/List_of_Falcon_9_and_Falcon_Heavy_launches'
static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/91.0.4472.124 Safari/537.36"
}

%%<br>
import required packages

In [3]:
import numpy as np, datetime as dt
import requests
from bs4 import BeautifulSoup
import re, unicodedata, pandas as pd
# %%
#  Helper function
def save_to_dict(launch_dict, row_id, elems):

    # Date value
    date_time = elems[columns_name.index("Date and time ( UTC )")-1]
    date_time = ' '.join(list(date_time.strings)[:2])
    date_time = dt.datetime.strptime(str(date_time), "%B %d, %Y %H:%M")
    launch_dict['Date and time ( UTC )'].append(date_time)
    launch_dict['Date'].append(date_time.date())
    launch_dict['Time'].append(date_time.time())

    # Booster version
    booster_version = elems[columns_name.index("Version, booster")-1]
    try:
        booster_version = ' '.join(booster_version.strings)
        booster_version = re.sub('[\xa0] ', '-', booster_version).replace(' ‑ ', '-')
    except:
        booster_version = None
        
    launch_dict['Version, booster'].append(booster_version)
    launch_dict['Version Booster'].append(booster_version)

    # Launch Site
    site = elems[columns_name.index('Launch site')-1]
    if site.strings:
        launch_site = ''.join(site.strings)
    else:
        launch_site = None
    launch_dict['Launch site'].append(launch_site)

    # Payload
    payload = elems[columns_name.index('Payload')-1]
    if payload.strings:
        payload = ''.join(payload.strings)
    else:
        payload = None
    launch_dict['Payload'].append(payload)

    # Payload Mass
    payload_mass = elems[columns_name.index('Payload mass')-1]
    if payload_mass.strings:
        payload_mass = ''.join(payload_mass.strings)
        payload_mass = re.sub('[\xa0]', ' ', payload_mass)
        payload_mass = payload_mass[:payload_mass.find('kg')+2]
    else:
        payload_mass = None
    launch_dict['Payload mass'].append(payload_mass)
    
    # Orbit
    orbit = elems[columns_name.index('Orbit')-1]
    if orbit.strings:
        orbit = ''.join(orbit.strings)
    else:
        orbit = None
    launch_dict['Orbit'].append(orbit)

    # Customer
    customer = elems[columns_name.index('Customer')-1]
    if customer.strings:
        customer = ''.join(customer.strings)
    else:
        customer = None
    launch_dict['Customer'].append(customer)

    # Launch outcome
    launch_outcome = elems[columns_name.index('Launch outcome')-1]
    if launch_outcome.strings:
        launch_outcome = ''.join(launch_outcome.strings)
    else:
        launch_outcome = None
    launch_dict['Launch outcome'].append(launch_outcome)

    # Booster landing
    booster_landing = elems[columns_name.index('Booster landing')-1]
    if booster_landing.strings:
        booster_landing = ''.join(booster_landing.strings)
    else:
        booster_landing = None
    launch_dict['Booster landing'].append(booster_landing)

In [4]:
def extract_column_from_header(row):
    """
    Return the landing status from the input HTML table cell
    """
    if row.br:
        row.br.replace_with(' ')
    for a_tag in row.find_all('a'):
        a_tag.replace_with(a_tag.get_text())
    if row.sup:
        row.sup.extract()
    column_name = ' '.join(row.stripped_strings)

    # Filter the digit and empty names
    if not (column_name.strip().isdigit()):
        return column_name.strip()

%%<br>
Request the Falcon9 Launch Wiki HTML

In [5]:
response = requests.get(wiki_url, headers=headers)
print('status code:', response.status_code)

status code: 200

%%<br>
Create a beautifulsoup object

In [6]:
soup = BeautifulSoup(response.text, features="html.parser", )
print(soup.title)
# %%
# Extract all columns/variable names from the HTML
html_tables = soup.find_all('table')

<title>List of Falcon 9 and Falcon Heavy launches - Wikipedia</title>

using the third table which is the first launch table

In [14]:
first_launch_table = html_tables[2]
print(first_launch_table)

<table class="wikitable plainrowheaders collapsible sticky-header" id="2025ytd" style="width: 100%;">
<tbody id="mwAUU"><tr id="mwAUY"><th id="mwAUc" scope="col">Flight No.</th>
<th id="mwAUg" scope="col">Date and time (UTC)</th>
<th id="mwAUs" scope="col">Version, booster</th>
<th id="mwAVI" scope="col">Launch site</th>
<th id="mwAVQ" scope="col">Payload</th>
<th id="mwAVk" scope="col">Payload mass</th>
<th id="mwAVo" scope="col">Orbit</th>
<th id="mwAVs" scope="col">Customer</th>
<th id="mwAVw" scope="col">Launch outcome</th>
<th id="mwAV4" scope="col">Booster landing</th></tr>
<tr id="F9-418">
<th id="mwAWE" rowspan="2" scope="row" style="text-align:center;">418</th>
<td id="mwAWI"><span about="#mwt180" data-mw='{"parts":[{"template":{"target":{"wt":"date table sorting","href":"./Template:Date_table_sorting"},"params":{"1":{"wt":"January 4, 2025"}},"i":0}}]}' data-sort-value="000000002025-01-04-0000" id="mwAWM" style="white-space:nowrap" typeof="mw:Transclusion">January 4, 2025</span><br id="mwAWQ"/>01:27<sup about="#mwt183" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-39"}}' id="cite_ref-39" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-39" id="mwAWU"><span class="mw-reflink-text" id="mwAWY"><span class="cite-bracket" id="mwAWc">[</span>28<span class="cite-bracket" id="mwAWg">]</span></span></a></sup></td>
<td id="mwAWk"><a href="//en.wikipedia.org/wiki/Falcon_9_Block_5" id="mwAWo" rel="mw:WikiLink" title="Falcon 9 Block 5">F9<span about="#mwt184" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nbsp","href":"./Template:Nbsp"},"params":{},"i":0}}]}' id="mwAWs" typeof="mw:Transclusion"><span typeof="mw:Entity"> </span></span>B5</a><br id="mwAWw"/><a href="//en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters#B1073" id="mwAW0" rel="mw:WikiLink" title="List of Falcon 9 first-stage boosters">B1073<span about="#mwt185" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAW4" typeof="mw:Transclusion mw:Entity">‑</span>20</a></td>
<td id="mwAW8"><a href="//en.wikipedia.org/wiki/Cape_Canaveral_Space_Force_Station" id="mwAXA" rel="mw:WikiLink" title="Cape Canaveral Space Force Station">Cape Canaveral</a>, <a href="//en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40" id="mwAXE" rel="mw:WikiLink" title="Cape Canaveral Space Launch Complex 40">SLC<span about="#mwt186" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAXI" typeof="mw:Transclusion mw:Entity">‑</span>40</a></td>
<td id="mwAXM"><a href="//en.wikipedia.org/wiki/Thuraya#Satellites" id="mwAXQ" rel="mw:WikiLink" title="Thuraya">Thuraya 4-NGS</a></td>
<td id="mwAXU"><span about="#mwt187" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"5000"},"2":{"wt":"kg"}},"i":0}}]}' id="mwAXY" typeof="mw:Transclusion">5,000</span><span about="#mwt187" typeof="mw:Entity"> </span><span about="#mwt187">kg (11,000</span><span about="#mwt187" typeof="mw:Entity"> </span><span about="#mwt187">lb)</span></td>
<td id="mwAXc"><a href="//en.wikipedia.org/wiki/Geostationary_transfer_orbit" id="mwAXg" rel="mw:WikiLink" title="Geostationary transfer orbit">GTO</a></td>
<td id="mwAXk"><a href="//en.wikipedia.org/wiki/Thuraya" id="mwAXo" rel="mw:WikiLink" title="Thuraya">Thuraya</a></td>
<td about="#mwt188" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}]}' id="mwAXs" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success</td>
<td about="#mwt189" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}," ([[A Shortfall of Gravitas|ASOG]])"]}' id="mwAXw" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success (<a class="mw-redirect" href="//en.wikipedia.org/wiki/A_Shortfall_of_Gravitas" rel="mw:WikiLink" title="A Shortfall of Gravitas">ASOG</a>)</td></tr>
<tr id="mwAX0">
<td colspan="9" id="mwAX4">Planned replacement for Thuraya 2 and 3.<sup about="#mwt192" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sn-20210908"},"body":{"id":"mw-reference-text-cite_note-sn-20210908-40"}}' id="cite_ref-sn-20210908_40-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-sn-20210908-40" id="mwAX8"><span class="mw-reflink-text" id="mwAYA"><span class="cite-bracket" id="mwAYE">[</span>29<span class="cite-bracket" id="mwAYI">]</span></span></a></sup><sup about="#mwt195" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-41"}}' id="cite_ref-41" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-41" id="mwAYM"><span class="mw-reflink-text" id="mwAYQ"><span class="cite-bracket" id="mwAYU">[</span>30<span class="cite-bracket" id="mwAYY">]</span></span></a></sup></td></tr>
<tr id="F9-419">
<th id="mwAYc" rowspan="2" scope="row" style="text-align:center;">419</th>
<td id="mwAYg"><span about="#mwt196" data-mw='{"parts":[{"template":{"target":{"wt":"date table sorting","href":"./Template:Date_table_sorting"},"params":{"1":{"wt":"January 6, 2025"}},"i":0}}]}' data-sort-value="000000002025-01-06-0000" id="mwAYk" style="white-space:nowrap" typeof="mw:Transclusion">January 6, 2025</span><br id="mwAYo"/>20:43<sup about="#mwt199" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-42"}}' id="cite_ref-42" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-42" id="mwAYs"><span class="mw-reflink-text" id="mwAYw"><span class="cite-bracket" id="mwAY0">[</span>31<span class="cite-bracket" id="mwAY4">]</span></span></a></sup></td>
<td id="mwAY8"><a href="//en.wikipedia.org/wiki/Falcon_9_Block_5" id="mwAZA" rel="mw:WikiLink" title="Falcon 9 Block 5">F9<span about="#mwt200" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nbsp","href":"./Template:Nbsp"},"params":{},"i":0}}]}' id="mwAZE" typeof="mw:Transclusion"><span typeof="mw:Entity"> </span></span>B5</a><br id="mwAZI"/><a href="//en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters#B1077" id="mwAZM" rel="mw:WikiLink" title="List of Falcon 9 first-stage boosters">B1077<span about="#mwt201" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAZQ" typeof="mw:Transclusion mw:Entity">‑</span>17</a></td>
<td id="mwAZU"><a href="//en.wikipedia.org/wiki/Cape_Canaveral_Space_Force_Station" id="mwAZY" rel="mw:WikiLink" title="Cape Canaveral Space Force Station">Cape Canaveral</a>, <a href="//en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40" id="mwAZc" rel="mw:WikiLink" title="Cape Canaveral Space Launch Complex 40">SLC<span about="#mwt202" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAZg" typeof="mw:Transclusion mw:Entity">‑</span>40</a></td>
<td id="mwAZk"><a href="//en.wikipedia.org/wiki/Starlink" id="mwAZo" rel="mw:WikiLink" title="Starlink">Starlink</a>: <a href="//en.wikipedia.org/wiki/List_of_Starlink_and_Starshield_launches#G6-71" id="mwAZs" rel="mw:WikiLink" title="List of Starlink and Starshield launches">Group<span id="mwAZw" typeof="mw:Entity"> </span>6<span about="#mwt203" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAZ0" typeof="mw:Transclusion mw:Entity">‑</span>71</a></td>
<td id="mwAZ4">~<span about="#mwt204" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"17500"},"2":{"wt":"kg"}},"i":0}}]}' id="mwAZ8" typeof="mw:Transclusion">17,500</span><span about="#mwt204" typeof="mw:Entity"> </span><span about="#mwt204">kg (38,600</span><span about="#mwt204" typeof="mw:Entity"> </span><span about="#mwt204">lb)</span></td>
<td id="mwAaA"><a href="//en.wikipedia.org/wiki/Low_Earth_orbit" id="mwAaE" rel="mw:WikiLink" title="Low Earth orbit">LEO</a></td>
<td id="mwAaI"><a href="//en.wikipedia.org/wiki/SpaceX" id="mwAaM" rel="mw:WikiLink" title="SpaceX">SpaceX</a></td>
<td about="#mwt205" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}]}' id="mwAaQ" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success</td>
<td about="#mwt206" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}," ([[Just Read the Instructions|JRTI]])"]}' id="mwAaU" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success (<a class="mw-redirect" href="//en.wikipedia.org/wiki/Just_Read_the_Instructions" rel="mw:WikiLink" title="Just Read the Instructions">JRTI</a>)</td></tr>
<tr id="mwAaY">
<td colspan="9" id="mwAac">Launch of 24 Starlink v2<span about="#mwt207" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nbsp","href":"./Template:Nbsp"},"params":{},"i":0}}]}' id="mwAag" typeof="mw:Transclusion"><span typeof="mw:Entity"> </span></span>mini satellites to a <span about="#mwt208" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"559"},"2":{"wt":"km"}},"i":0}}]}' id="mwAak" typeof="mw:Transclusion">559</span><span about="#mwt208" typeof="mw:Entity"> </span><span about="#mwt208">km (347</span><span about="#mwt208" typeof="mw:Entity"> </span><span about="#mwt208">mi)</span> orbit at an inclination of 43° to expand internet constellation. 1st time flying a fairing half for the 23rd time.</td></tr>
<tr id="F9-420">
<th id="mwAao" rowspan="2" scope="row" style="text-align:center;">420</th>
<td id="mwAas"><span about="#mwt209" data-mw='{"parts":[{"template":{"target":{"wt":"date table sorting","href":"./Template:Date_table_sorting"},"params":{"1":{"wt":"January 8, 2025"}},"i":0}}]}' data-sort-value="000000002025-01-08-0000" id="mwAaw" style="white-space:nowrap" typeof="mw:Transclusion">January 8, 2025</span><br id="mwAa0"/>15:27<sup about="#mwt212" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-43"}}' id="cite_ref-43" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-43" id="mwAa4"><span class="mw-reflink-text" id="mwAa8"><span class="cite-bracket" id="mwAbA">[</span>32<span class="cite-bracket" id="mwAbE">]</span></span></a></sup></td>
<td id="mwAbI"><a href="//en.wikipedia.org/wiki/Falcon_9_Block_5" id="mwAbM" rel="mw:WikiLink" title="Falcon 9 Block 5">F9<span about="#mwt213" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nbsp","href":"./Template:Nbsp"},"params":{},"i":0}}]}' id="mwAbQ" typeof="mw:Transclusion"><span typeof="mw:Entity"> </span></span>B5</a><br id="mwAbU"/><a href="//en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters#B1086" id="mwAbY" rel="mw:WikiLink" title="List of Falcon 9 first-stage boosters">B1086<span about="#mwt214" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAbc" typeof="mw:Transclusion mw:Entity">‑</span>3</a></td>
<td id="mwAbg"><a href="//en.wikipedia.org/wiki/Kennedy_Space_Center" id="mwAbk" rel="mw:WikiLink" title="Kennedy Space Center">Kennedy</a>, <a href="//en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39A" id="mwAbo" rel="mw:WikiLink" title="Kennedy Space Center Launch Complex 39A">LC<span about="#mwt215" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAbs" typeof="mw:Transclusion mw:Entity">‑</span>39A</a></td>
<td id="mwAbw"><a href="//en.wikipedia.org/wiki/Starlink" id="mwAb0" rel="mw:WikiLink" title="Starlink">Starlink</a>: <a href="//en.wikipedia.org/wiki/List_of_Starlink_and_Starshield_launches#G12-11" id="mwAb4" rel="mw:WikiLink" title="List of Starlink and Starshield launches">Group<span id="mwAb8" typeof="mw:Entity"> </span>12-11</a> (21<span id="mwAcA" typeof="mw:Entity"> </span>satellites)</td>
<td id="mwAcE">~<span about="#mwt216" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"16500"},"2":{"wt":"kg"}},"i":0}}]}' id="mwAcI" typeof="mw:Transclusion">16,500</span><span about="#mwt216" typeof="mw:Entity"> </span><span about="#mwt216">kg (36,400</span><span about="#mwt216" typeof="mw:Entity"> </span><span about="#mwt216">lb)</span></td>
<td id="mwAcM"><a href="//en.wikipedia.org/wiki/Low_Earth_orbit" id="mwAcQ" rel="mw:WikiLink" title="Low Earth orbit">LEO</a></td>
<td id="mwAcU"><a href="//en.wikipedia.org/wiki/SpaceX" id="mwAcY" rel="mw:WikiLink" title="SpaceX">SpaceX</a></td>
<td about="#mwt217" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}]}' id="mwAcc" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success</td>
<td about="#mwt218" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}," ([[A Shortfall of Gravitas|ASOG]])"]}' id="mwAcg" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success (<a class="mw-redirect" href="//en.wikipedia.org/wiki/A_Shortfall_of_Gravitas" rel="mw:WikiLink" title="A Shortfall of Gravitas">ASOG</a>)</td></tr>
<tr id="mwAck">
<td colspan="9" id="mwAco">Launch of 21 Starlink v2<span id="mwAcs" typeof="mw:Entity"> </span>mini satellites, including 13 with direct-to-cell connectivity, to a <span about="#mwt219" data-mw='{"parts":[{"template":{"target":{"wt":"cvt","href":"./Template:Cvt"},"params":{"1":{"wt":"559"},"2":{"wt":"km"}},"i":0}}]}' id="mwAcw" typeof="mw:Transclusion">559</span><span about="#mwt219" typeof="mw:Entity"> </span><span about="#mwt219">km (347</span><span about="#mwt219" typeof="mw:Entity"> </span><span about="#mwt219">mi)</span> orbit at an inclination of 43° to expand internet constellation.</td></tr>
<tr id="F9-421">
<th id="mwAc0" rowspan="2" scope="row" style="text-align:center;">421</th>
<td id="mwAc4"><span about="#mwt220" data-mw='{"parts":[{"template":{"target":{"wt":"date table sorting","href":"./Template:Date_table_sorting"},"params":{"1":{"wt":"January 10, 2025"}},"i":0}}]}' data-sort-value="000000002025-01-10-0000" id="mwAc8" style="white-space:nowrap" typeof="mw:Transclusion">January 10, 2025</span><br id="mwAdA"/>03:53<sup about="#mwt223" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-44"}}' id="cite_ref-44" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-44" id="mwAdE"><span class="mw-reflink-text" id="mwAdI"><span class="cite-bracket" id="mwAdM">[</span>33<span class="cite-bracket" id="mwAdQ">]</span></span></a></sup></td>
<td id="mwAdU"><a href="//en.wikipedia.org/wiki/Falcon_9_Block_5" id="mwAdY" rel="mw:WikiLink" title="Falcon 9 Block 5">F9<span about="#mwt224" class="nowrap" data-mw='{"parts":[{"template":{"target":{"wt":"nbsp","href":"./Template:Nbsp"},"params":{},"i":0}}]}' id="mwAdc" typeof="mw:Transclusion"><span typeof="mw:Entity"> </span></span>B5</a><br id="mwAdg"/><a href="//en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters#B1071" id="mwAdk" rel="mw:WikiLink" title="List of Falcon 9 first-stage boosters">B1071<span about="#mwt225" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAdo" typeof="mw:Transclusion mw:Entity">‑</span>22</a></td>
<td id="mwAds"><a href="//en.wikipedia.org/wiki/Vandenberg_Space_Force_Base" id="mwAdw" rel="mw:WikiLink" title="Vandenberg Space Force Base">Vandenberg</a>, <a href="//en.wikipedia.org/wiki/Vandenberg_Space_Launch_Complex_4" id="mwAd0" rel="mw:WikiLink" title="Vandenberg Space Launch Complex 4">SLC<span about="#mwt226" data-mw='{"parts":[{"template":{"target":{"wt":"nbhyph","href":"./Template:Nbhyph"},"params":{},"i":0}}]}' id="mwAd4" typeof="mw:Transclusion mw:Entity">‑</span>4E</a></td>
<td id="mwAd8">NROL-153 (22<span id="mwAeA" typeof="mw:Entity"> </span><a href="//en.wikipedia.org/wiki/SpaceX_Starshield" id="mwAeE" rel="mw:WikiLink" title="SpaceX Starshield">Starshield</a> satellites)<sup about="#mwt229" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-45"}}' id="cite_ref-45" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-45" id="mwAeI"><span class="mw-reflink-text" id="mwAeM"><span class="cite-bracket" id="mwAeQ">[</span>34<span class="cite-bracket" id="mwAeU">]</span></span></a></sup></td>
<td about="#mwt230" class="table-na" data-mw='{"parts":["| ",{"template":{"target":{"wt":"n/a","href":"./Template:N/a"},"params":{"1":{"wt":"Unknown"}},"i":0}}]}' data-sort-value="" id="mwAeY" style="background: var(--background-color-interactive, #ececec); color: var(--color-base, inherit); vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Unknown</td>
<td id="mwAec"><a href="//en.wikipedia.org/wiki/Low_Earth_orbit" id="mwAeg" rel="mw:WikiLink" title="Low Earth orbit">LEO</a></td>
<td id="mwAek"><a href="//en.wikipedia.org/wiki/National_Reconnaissance_Office" id="mwAeo" rel="mw:WikiLink" title="National Reconnaissance Office">NRO</a></td>
<td about="#mwt231" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}]}' id="mwAes" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success</td>
<td about="#mwt232" class="table-success" data-mw='{"parts":["| ",{"template":{"target":{"wt":"Success","href":"./Template:Success"},"params":{},"i":0}}," ([[Of Course I Still Love You|OCISLY]])"]}' id="mwAew" style="background: #9EFF9E; color:black; vertical-align: middle; text-align: center; " typeof="mw:Transclusion">Success (<a class="mw-redirect" href="//en.wikipedia.org/wiki/Of_Course_I_Still_Love_You" rel="mw:WikiLink" title="Of Course I Still Love You">OCISLY</a>)</td></tr>
<tr id="mwAe0">
<td colspan="9" id="mwAe4">Seventh launch of SpaceX/Northrop Grumman-built satellites for the National Reconnaissance Office.</td></tr>
<tr id="F9-422">
<th id="mwAe8" rowspan="2" scope="row" style="text-align:center;">422</th>
<td id="mwAfA"><span about="#mwt233" data-mw='{"parts":[{"template":{"target":{"wt":"date table sorting","href":"./Template:Date_table_sorting"},"params":{"1":{"wt":"January 10, 2025"}},"i":0}}]}' data-sort-value="000000002025-01-10-0000" id="mwAfE" style="white-space:nowrap" typeof="mw:Transclusion">January 10, 2025</span><br id="mwAfI"/>19:11<sup about="#mwt236" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-46"}}' id="cite_ref-46" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-46" id="mwAfM"><span class="mw-reflink-text" id="mwAfQ"><span class="cite-bracket" id="mwAfU">[</span>35<span class="cite-bracket" id="mwAfY">]</span></span></a></sup></td>

In [8]:
columns_name = []
for th in first_launch_table.find_all('tr')[0].find_all('th'): # all headers in first row
    columns_name.append(extract_column_from_header(th))

In [9]:
print(columns_name)
# %%
# Create dataframe from HTML table
launch_dict = {k: [] for k in columns_name}

['Flight No.', 'Date and time ( UTC )', 'Version, booster', 'Launch site', 'Payload', 'Payload mass', 'Orbit', 'Customer', 'Launch outcome', 'Booster landing']

Add some new columns

In [10]:
launch_dict['Version Booster']=[]
launch_dict['Booster landing']=[]
launch_dict['Date']=[]
launch_dict['Time']=[]

Parsing into dict<br>
Extract each table of class "wikitable plainrowheaders collapsible sticky-header"

In [11]:
for table_number, table in enumerate(soup.find_all('table',
    attrs={'class':"wikitable plainrowheaders collapsible sticky-header"}) ):
    # get table row
    print('\ntable', table_number)
    for row in table.find_all("tr"):
        # check if it is a row
        if row.th and row.th['scope']=='row':
            # get number for Flight No.
            flight_number = row.th.string.strip()
            try:
                row_id = int(flight_number)
            except:
                row_id = str(flight_number)

            # print(flight_number)
            # get row elements
            elems = row.find_all('td')
            # if the row's elements match the number of columns ( minus "Flight No.")
            if len(elems) == 9:                
                save_to_dict(launch_dict, row_id, elems)
                # Flight Number 
                launch_dict['Flight No.'].append(row_id)
                # print(launch_dict['Flight No.'])

table 0

table 1

%%<br>
Creating data frame from dictionary

In [12]:
df = pd.DataFrame({ key:pd.Series(value) for key, value in launch_dict.items() })

In [16]:
## Checking Data frame
df.head()

,Flight No.,Date and time ( UTC ),"Version, booster",Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Booster landing,Version Booster,Date,Time
0,418,2025-01-04 01:27:00,F9 -B5 B1073-20,"Cape Canaveral, SLC‑40",Thuraya 4-NGS,"5,000 kg",GTO,Thuraya,Success,Success (ASOG),F9 -B5 B1073-20,2025-01-04,01:27:00
1,419,2025-01-06 20:43:00,F9 -B5 B1077-17,"Cape Canaveral, SLC‑40",Starlink: Group 6‑71,"~17,500 kg",LEO,SpaceX,Success,Success (JRTI),F9 -B5 B1077-17,2025-01-06,20:43:00
2,420,2025-01-08 15:27:00,F9 -B5 B1086-3,"Kennedy, LC‑39A",Starlink: Group 12-11 (21 satellites),"~16,500 kg",LEO,SpaceX,Success,Success (ASOG),F9 -B5 B1086-3,2025-01-08,15:27:00
3,421,2025-01-10 03:53:00,F9 -B5 B1071-22,"Vandenberg, SLC‑4E",NROL-153 (22 Starshield satellites)[34],U,LEO,NRO,Success,Success (OCISLY),F9 -B5 B1071-22,2025-01-10,03:53:00
4,422,2025-01-10 19:11:00,F9 -B5 B1067-25,"Cape Canaveral, SLC‑40",Starlink: Group 12-12 (21 satellites),"~16,500 kg",LEO,SpaceX,Success,Success (JRTI),F9 -B5 B1067-25,2025-01-10,19:11:00

In [17]:
df.sample(5)

,Flight No.,Date and time ( UTC ),"Version, booster",Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Booster landing,Version Booster,Date,Time
107,525,2025-08-31 11:49:00,F9 -B5 B1077-23,"Cape Canaveral, SLC‑40",Starlink: Group 10-14,"~16,100 kg",LEO,SpaceX,Success,Success (JRTI),F9 -B5 B1077-23,2025-08-31,11:49:00
39,457,2025-04-07 23:06:00,F9 -B5 B1093-1,"Vandenberg, SLC‑4E",Starlink: Group 11-11,"~15,500 kg",LEO,SpaceX,Success,Success (OCISLY),F9 -B5 B1093-1,2025-04-07,23:06:00
10,428,2025-01-24 14:07:00,F9 -B5 B1063-23,"Vandenberg, SLC‑4E",Starlink: Group 11-6 (23 satellites),"~17,100 kg",LEO,SpaceX,Success,Success (OCISLY),F9 -B5 B1063-23,2025-01-24,14:07:00
20,438,2025-02-18 23:21:00,F9 -B5 B1080-16,"Cape Canaveral, SLC‑40",Starlink: Group 10-12 (23 satellites),"~17,100 kg",LEO,SpaceX,Success,Success (JRTI),F9 -B5 B1080-16,2025-02-18,23:21:00
211,629,2026-04-19 16:03:00,F9 -B5 B1097-8,"Vandenberg, SLC‑4E",Starlink: Group 17-22,"~14,375 kg",LEO,SpaceX,Success,Success (OCISLY),F9 -B5 B1097-8,2026-04-19,16:03:00

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Flight No.             245 non-null    object
 1   Date and time ( UTC )  245 non-null    datetime64[us]
 2   Version, booster       245 non-null    str
 3   Launch site            245 non-null    str
 4   Payload                245 non-null    str
 5   Payload mass           245 non-null    str
 6   Orbit                  245 non-null    str
 7   Customer               245 non-null    str
 8   Launch outcome         245 non-null    str
 9   Booster landing        245 non-null    str
 10  Version Booster        245 non-null    str
 11  Date                   245 non-null    object
 12  Time                   245 non-null    object
dtypes: datetime64[us](1), object(3), str(9)
memory usage: 25.0+ KB

In [19]:
df.describe(include='all')

,Flight No.,Date and time ( UTC ),"Version, booster",Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Booster landing,Version Booster,Date,Time
count,245.0,245,245,245,245,245,245,245,245,245,245,245,245
unique,245.0,NaN,245,5,245,45,9,32,1,9,245,220,226
top,418.0,NaN,F9 -B5 B1073-20,"Cape Canaveral, SLC‑40",Thuraya 4-NGS,"~16,675 kg",LEO,SpaceX,Success,Success (OCISLY),F9 -B5 B1073-20,2025-01-10,02:09:00
freq,1.0,NaN,1,111,1,43,158,185,245,93,1,2,3
mean,NaN,2025-10-03 02:32:59.755102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,2025-01-04 01:27:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2025-05-24 17:19:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,2025-09-26 04:26:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2026-02-16 07:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,2026-07-07 07:12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

%%<br>
Save to csv

In [20]:
df.to_csv('data/spacex_web_scraped.csv', index=False)
# %%